image: python:3.6-stretch

stages:
  - deploy

pages:
  stage: deploy
  when: on_success
  only:
    - master
  script:
    - mkdir public
    - cd docs
    - make html
    - mv _build/html/* ../public/
  artifacts:
    paths:
      - public
deploy-Staging:  
   stage: deploy  
   before_script:
      - mkdir -p ~/.ssh     
      - echo -e "$STAGING_KEY" > ~/.ssh/id_rsa    
      - chmod 600 ~/.ssh/id_rsa     
      - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'  
   script:  
      - ssh -p3322 e4esysadmin@172.93.48.21 "cd HealthThink_Frontend && git pull && npm run build && sudo systemctl restart nginx "  
   environment:    
     name: Staging 
   only:   
     refs:      
       - Staging  
   when: manual


